#!/usr/bin/env python3
"""Validation script for the variable smoothing length implementation.

Runs the `mlh` binary on a short config (a few output dumps), then walks the
resulting HDF5 dumps and checks:

  1. mass, volume, momentum and energy are preserved relative to dump 0
  2. no NaN / inf in any stored field
  3. sml stays within a sensible band around the analytic target
     h_target = delta_p * sqrt(N_NN / pi)   (2D)

Exits 0 on pass, 1 on fail. Prints a short per-dump summary either way.

Typical use:

    # build with VARIABLE_SML=1 in parameter.h
    cd demonstrator && make all
    python3 ../testcases/single_block/validate_sml.py

By default it invokes `demonstrator/bin/mlh` with the
`testcases/single_block/config_smlvalidation.info` config, which this script
writes on the fly into a scratch directory so that repeated runs do not
touch user configs.
"""

import argparse
import math
import os
import shutil
import subprocess
import sys

import h5py
import numpy as np


DEFAULT_DEMO_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "demonstrator")
)
DEFAULT_IC = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "single_block_deltap0.005-2D.h5")
)

# Tolerances. Mass, volume and momentum are strictly conserved in MFM and
# get a tight cap. Kinetic+internal energy is NOT strictly conserved when
# ELASTIC=1 because strain energy is not tracked here, so energy is a warning
# rather than a hard failure. The sml band is generous — we only want to
# catch runaway / NaN, not the natural broadening that a shearing block
# produces as some regions compress and others stretch.
MASS_REL_TOL   = 1e-10
VOL_REL_TOL    = 1e-3   # volume can drift slightly via compPressure/EOS
MOM_REL_TOL    = 1e-6   # relative to initial kinetic-momentum scale
ENERGY_REL_TOL = 0.5    # warn only
SML_BAND_LO    = 0.25   # sml must stay > 0.25 * h_target
SML_BAND_HI    = 4.0    # sml must stay < 4.0  * h_target


def write_config(path, ic_path, out_dir, nnn_target, kernel_size, time_end):
    """Write a self-contained scratch config file for the test run."""
    # Make the dump stride fine enough that `time_end` yields >=2 dumps.
    # The demonstrator aborts with exit(9) if time_end < timeStep.
    time_step = min(0.01, max(time_end / 5.0, 1e-4))
    with open(path, "w") as f:
        f.write("; auto-generated by validate_sml.py\n")
        f.write(f"initFile {ic_path}\n")
        f.write(f"outDir   {out_dir}\n")
        f.write(f"timeStep {time_step}\n")
        f.write(f"timeEnd  {time_end}\n")
        f.write(f"h5DumpInterval 1\n")
        f.write("periodicBoxLimits {\n")
        f.write("    lowerX -0.25\n    lowerY -0.25\n    lowerZ  0.\n")
        f.write("    upperX  0.25\n    upperY  0.25\n    upperZ  0.\n")
        f.write("}\n")
        f.write(f"kernelSize {kernel_size}\n")
        f.write("hydro_gamma 1.6666666666666667\n")
        f.write("MURN_K0   1.0\nMURN_n    2.0\nMURN_rho0 1.0\n")
        f.write("sml {\n")
        f.write(f"    NNNTarget {nnn_target}\n")
        f.write("    tol       1e-3\n")
        f.write("    maxIter   20\n")
        f.write("    maxFactor 1.2\n")
        f.write("}\n")


def load_dump(path):
    d = {}
    with h5py.File(path, "r") as f:
        for k in ("m", "x", "v", "u", "rho", "P", "sml"):
            if k in f:
                d[k] = f[k][:]
        d["time"] = float(f["time"][0]) if "time" in f else 0.0
    return d


def has_nans(d):
    for k, v in d.items():
        if isinstance(v, np.ndarray) and not np.all(np.isfinite(v)):
            return k
    return None


def totals(d):
    m = d["m"]
    v = d["v"]
    u = d["u"]
    rho = d["rho"]
    M = float(np.sum(m))
    V = float(np.sum(m / rho))
    Px = float(np.sum(m * v[:, 0]))
    Py = float(np.sum(m * v[:, 1]))
    # internal + kinetic
    kin = 0.5 * np.sum(m * (v[:, 0] ** 2 + v[:, 1] ** 2))
    E = float(np.sum(m * u) + kin)
    return dict(M=M, V=V, Px=Px, Py=Py, E=E)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--demo-dir", default=DEFAULT_DEMO_DIR,
                    help="demonstrator/ directory containing bin/mlh")
    ap.add_argument("--ic", default=DEFAULT_IC,
                    help="path to the IC HDF5 file")
    ap.add_argument("--nnn-target", type=float, default=50.0)
    ap.add_argument("--kernel-size", type=float, default=0.02)
    ap.add_argument("--delta-p", type=float, default=0.005,
                    help="particle spacing in the IC (for analytic h check)")
    ap.add_argument("--time-end", type=float, default=0.02,
                    help="simulation time end (default is very short on the "
                         "10k-particle single_block IC; increase for a "
                         "longer-range conservation check)")
    ap.add_argument("--keep-output", action="store_true",
                    help="don't wipe the scratch output dir on exit")
    args = ap.parse_args()

    scratch = os.path.join(os.path.dirname(__file__), "output_smlvalidation")
    if os.path.isdir(scratch):
        shutil.rmtree(scratch)
    os.makedirs(scratch, exist_ok=True)
    cfg_path = os.path.join(os.path.dirname(__file__),
                            "config_smlvalidation.info")
    write_config(cfg_path, args.ic, scratch, args.nnn_target,
                 args.kernel_size, args.time_end)

    bin_path = os.path.join(args.demo_dir, "bin", "mlh")
    if not os.path.isfile(bin_path):
        print(f"FAIL: mlh binary not found at {bin_path}", file=sys.stderr)
        return 1

    # Run the simulation. Logs are captured but kept short by piping through
    # a grep-equivalent.
    print(f"[validate_sml] running {bin_path} -c {cfg_path}")
    proc = subprocess.run([bin_path, "-c", cfg_path], cwd=args.demo_dir,
                          capture_output=True, text=True)
    if proc.returncode != 0:
        print("FAIL: mlh exited with", proc.returncode, file=sys.stderr)
        print(proc.stderr[-2000:], file=sys.stderr)
        return 1

    dumps = sorted(os.path.join(scratch, f)
                   for f in os.listdir(scratch) if f.endswith(".h5"))
    if len(dumps) < 2:
        print(f"FAIL: expected at least 2 dumps, got {len(dumps)}",
              file=sys.stderr)
        return 1

    h_target = args.delta_p * math.sqrt(args.nnn_target / math.pi)
    print(f"[validate_sml] analytic h_target = {h_target:.6f}")

    ref = None
    failed = False
    for i, dp in enumerate(dumps):
        d = load_dump(dp)
        bad = has_nans(d)
        if bad is not None:
            print(f"  dump {i}: FAIL NaN in '{bad}'")
            failed = True
            continue
        tot = totals(d)
        if ref is None:
            ref = tot
            print(f"  dump {i}: M={tot['M']:.8f} V={tot['V']:.8f} "
                  f"E={tot['E']:.6e} |p|={math.hypot(tot['Px'], tot['Py']):.2e}")
        else:
            dM = abs(tot["M"] - ref["M"]) / abs(ref["M"])
            dV = abs(tot["V"] - ref["V"]) / abs(ref["V"])
            dE = abs(tot["E"] - ref["E"]) / max(abs(ref["E"]), 1e-30)
            # momentum: compare to an initial kinetic-momentum scale so we
            # don't demand absolute zero on a non-symmetric IC
            mom_scale = max(math.hypot(ref["Px"], ref["Py"]),
                            math.sqrt(2. * ref["M"] * max(ref["E"], 1e-30)))
            dP = math.hypot(tot["Px"] - ref["Px"],
                            tot["Py"] - ref["Py"]) / mom_scale
            line = (f"  dump {i}: dM/M={dM:.1e} dV/V={dV:.1e} "
                    f"dE/E={dE:.1e} dP/P={dP:.1e}")
            local_fail = False
            if dM > MASS_REL_TOL:
                line += " [mass drift]"
                local_fail = True
            if dV > VOL_REL_TOL:
                line += " [volume drift]"
                local_fail = True
            if dP > MOM_REL_TOL:
                line += " [momentum drift]"
                local_fail = True
            if dE > ENERGY_REL_TOL:
                line += " [energy WARN]"  # warning only, not a failure
            print(line + ("  FAIL" if local_fail else "  ok"))
            if local_fail:
                failed = True
        if "sml" in d:
            sml = d["sml"]
            lo = SML_BAND_LO * h_target
            hi = SML_BAND_HI * h_target
            bandOk = bool(np.all((sml > lo) & (sml < hi)))
            print(f"           sml[min/mean/max] = {sml.min():.6f} / "
                  f"{sml.mean():.6f} / {sml.max():.6f}"
                  f"   (in [{lo:.4f}, {hi:.4f}]: {bandOk})")
            if not bandOk:
                failed = True
        else:
            print("           WARNING: /sml not found — "
                  "is VARIABLE_SML enabled in parameter.h?")

    if not args.keep_output:
        shutil.rmtree(scratch, ignore_errors=True)
        try:
            os.remove(cfg_path)
        except FileNotFoundError:
            pass

    if failed:
        print("\n[validate_sml] RESULT: FAIL")
        return 1
    print("\n[validate_sml] RESULT: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
